name: fair_fares_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas>=1.3.0
  - numpy>=1.20.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - folium>=0.12.0
  - sqlite3
  - jupyter
  - pip
  - pip:
    - jupyter-black
    - nbformat>=5.0.0